### ISSUE TITLE
scala + antlr as target - generate tokens for other languages

### ISSUE THREAD

**Issue by johndpope** [bdkent/antlr4-scala-target-example#1]
Hi I'm looking for the ability to target antlr to scala to produce other tokenised classes in scala for python.
I have this ticket open - but wondered if you could shed any light on this?
https://github.com/yahoojapan/objc2swift/issues/22

I'm looking for a line of code like this 

```
  java -cp antlr4-4.5.1.jar  org.antlr.v4.Tool -Dlanguage=Swift -visitor -o gen ObjC.g4
```

<img width="525" alt="screen shot 2016-04-28 at 9 06 10 pm" src="https://cloud.githubusercontent.com/assets/289994/14906551/72343c34-0d8a-11e6-9415-a2c35e49d1dc.png">
(I got this from https://github.com/janyou/ANTLR-Swift-Target)

But in my case - I want to use your scala language target and use a python.g4 grammar file

```
java -cp antlr4-scala-target-0.0.1-SNAPSHOT.jar  org.antlr.v4.Tool -Dlanguage=scala -visitor -o gen python.g4
```

(I then want to switch out the objc2swift and try converting python to swift)

When I build and install this project - 
mvn install
it succeeds 
but the corresponding antlr jar file  is only antlr4-scala-target-0.0.1-SNAPSHOT.jar is 40kb
The jar in first example is the antlr 1.3 MB file
any ideas?

I tried to inject your updated targets using this - but not working. 

```
jar uf antlr4-4.5.1.jar /antlr4-scala-target/src/*
```

I inspect the jar file and update the paths - to match / but still get this error

```
  ANTLR cannot generate Scala code as of version 4.5.1
```

UPDATE 

So I think the path in this repo is out of date. There seems to be a nested target folder now. 

`org.antlr.v4.Tool -Dlanguage=Scala -visitor -o gen Hello.g4
Exception in thread "main" java.lang.NoClassDefFoundError: org/antlr/v4/codegen/target/ScalaTarget (wrong name: org/antlr/v4/codegen/ScalaTarget)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at org.antlr.v4.codegen.CodeGenerator.targetExists(CodeGenerator.java:89)
    at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:402)
    at org.antlr.v4.Tool.process(Tool.java:378)
    at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:345)
    at org.antlr.v4.Tool.main(Tool.java:192)`

**Comment by johndpope** [comment]
I thought I could glue the two jar files together - using this / but no joy.
http://stackoverflow.com/questions/5080220/how-to-combine-two-jar-files
Extract -> antlr4-4.5.1.jar 
Extract -> antlr4-scala-target-0.0.1-SNAPSHOT.jar

cd antlr4-4.5.1
(merge the contents of scala-target into this folder)
jar -cvf jar3.jar .

java -cp jar3.jar  org.antlr.v4.Tool -Dlanguage=Scala -visitor -o gen Python3.g4
error(31):  ANTLR cannot generate Scala code as of version 4.5.1

**Comment by johndpope** [comment]
fyi https://github.com/johndpope/ANTLR-Swift-Target/tree/master/gen/grammars-v4
